# -*- coding: utf-8 -*-
"""3.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_2gmTlXjsHx8oGsSuK2ahktw6DhYGJb
"""

for i in range(1,4+1):
    print('*'*i)
#or
n=eval(input("請問要幾行?"))
for i in range(1,n+1):
    print('*'*i)

