# -*- coding: utf-8 -*-
"""3.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7w58hV2Rh_FCYsQfnoEi8DUyzxwwGjj
"""

for i in range(1,5):
    i=5-i
    print('*'*i)
#or
n=eval(input("請問要幾行?"))
for i in range(1,n+1):
    i=n-i+1
    print('*'*i)

