# -*- coding: utf-8 -*-
"""4.11.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8O5Igoew09pbRD5K5S9EGX15R68bARU
"""

import math
def f(x, n):
    z=math.pow(x,n)
    return z
x=eval(input("底數="))
n=eval(input("指數="))
p=f(x, n)
print(p)

