# -*- coding: utf-8 -*-
"""4.9.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laO5y1qpmYr9x6BsU0Ww3BxzqbkD43j8
"""

#4.9.1
#試運行以下列程式並解釋之:
def print_twice(text):
    print(text)
    print(text)

def cat_twice(part1, part2):
    cat = part1 + part2
    print_twice(text=cat)

line1 = '觀自在菩薩。'
line2 = '行深波若波羅蜜多時。'
cat_twice(part1=line1, part2=line2)
#答：print_twice(text)使輸入列印兩遍；cat_twice(part1, part2)使字串相接；cat_twice(part1=line1, part2=line2)使變數line1與變數line2的內容相接，然後列印兩遍。

#4.9.2
#試解釋下式結果
def print_twice(text):
    print(text)
    print(text)

def cat_twice(part1, part2):
    cat = part1 + part2
    print_twice(text=cat)

line1 = '觀自在菩薩。'
line2 = '行深波若波羅蜜多時。'
cat_twice(part1=line1, part2=line2)
print(cat)
#"cat"是函式中變數，是局部的，無法於主程式層級直接讀取。

#引自王昱鈞老師講義雲端:https://drive.google.com/drive/folders/1gThJtbDOsVzGI34yT_2JrY5DG125wjfq

#4.10.1
def compare_value(x, y):
    if x>y:
        return 1
    elif x==y:
        return 0
    else :
        return -1
x=eval(input("x="))
y=eval(input("y="))
z=compare_value(x,y)
print(z)

